"""Infrastructure implementations for durable AgentKernel state."""

from agentkernel.storage.control import (
    CapabilityBudget,
    CapabilityChainReservation,
    CapabilityReservationFence,
    CapabilityReservationState,
    DecisionKind,
    DecisionSnapshot,
    IntentAcquisition,
    IntentAttemptRecord,
    IntentAttemptState,
    IntentDisposition,
    IntentHistoryEntry,
    SQLiteControlStore,
    StoredNormalizedAction,
    decision_snapshot_digest,
    decision_snapshot_row_digest,
)
from agentkernel.storage.enforced import (
    AuthorizationResult,
    CommitDispatchResult,
    DispatchClassificationResult,
    EnforcedStoreDisposition,
    EnforcedTransactionResult,
    LateRecoveryResult,
    PlanningResult,
    ReconciliationResult,
    RecoveryAuthorizationResult,
    RecoveryClaimPreview,
    RecoveryClaimResult,
    RecoveryCursor,
    RecoveryFinishResult,
    RecoveryScanPage,
    SQLiteEnforcedTransactionStore,
    StageMaterialResult,
    WorkerLeaseResult,
    capability_reservation_digest,
    capability_reservation_plan_digest,
    preview_committed_capability_reservation,
)
from agentkernel.storage.sqlite import IntentReservation, SQLiteJournal
from agentkernel.transactions.contracts import (
    DispatchEvidenceUnavailableRecord,
    RecoveryEvidenceUnavailableRecord,
)

__all__ = [
    "AuthorizationResult",
    "CapabilityBudget",
    "CapabilityChainReservation",
    "CapabilityReservationFence",
    "CapabilityReservationState",
    "CommitDispatchResult",
    "DecisionKind",
    "DecisionSnapshot",
    "DispatchClassificationResult",
    "DispatchEvidenceUnavailableRecord",
    "EnforcedStoreDisposition",
    "EnforcedTransactionResult",
    "IntentAcquisition",
    "IntentAttemptRecord",
    "IntentAttemptState",
    "IntentDisposition",
    "IntentHistoryEntry",
    "IntentReservation",
    "LateRecoveryResult",
    "PlanningResult",
    "ReconciliationResult",
    "RecoveryAuthorizationResult",
    "RecoveryClaimPreview",
    "RecoveryClaimResult",
    "RecoveryCursor",
    "RecoveryEvidenceUnavailableRecord",
    "RecoveryFinishResult",
    "RecoveryScanPage",
    "SQLiteControlStore",
    "SQLiteEnforcedTransactionStore",
    "SQLiteJournal",
    "StageMaterialResult",
    "StoredNormalizedAction",
    "WorkerLeaseResult",
    "capability_reservation_digest",
    "capability_reservation_plan_digest",
    "decision_snapshot_digest",
    "decision_snapshot_row_digest",
    "preview_committed_capability_reservation",
]
